Fix log exception
When running the test
...test_cluster.ClusteredAPITestCase.test_cluster_proxy_stale_revision
we get the exception below:

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "/home/gkotton/vmware-nsx/.tox/py27/local/lib/python2.7/site-packages/neutron_lib/exceptions.py", line 48, in __unicode__
    return unicode(self.msg)
AttributeError: 'StaleRevision' object has no attribute 'msg'
Logged from file cluster.py, line 418

Change-Id: I4ce6b90b3dbd2fd1a2987fafb1034fdd0cd05a60
(cherry picked from commit 640ac29a1eb46c3ad0de992c347f9c5cf7caa9bc)